const sampleListings = [
  {
    title: "Royal Haveli Heritage Stay",
    description: "Traditional Rajasthani haveli with heritage interiors, courtyard dining, and a private pool. Experience royalty in the Pink City.",
    image: { url: "https://res.cloudinary.com/dgu8te3bn/image/upload/v1771086037/Homekuti_DEV/pkrc2pivxsp5l56swdob.webp", filename: "Homekuti_DEV/pkrc2pivxsp5l56swdob" },
    price: 2200, location: "Jaipur", country: "India",
    genre: "Heritage",
    geometry: { type: "Point", coordinates: [75.8189817, 26.9154576] },
  },
  {
    title: "Portuguese Villa Stay",
    description: "Stunning Portuguese-style villa tucked in the lush hills of Goa. Enjoy a serene retreat with colonial architecture and a private garden.",
    image: { url: "https://res.cloudinary.com/dgu8te3bn/image/upload/v1771086213/Homekuti_DEV/m1yqqivq2yjcggrsjaov.jpg", filename: "Homekuti_DEV/m1yqqivq2yjcggrsjaov" },
    price: 2800, location: "Goa", country: "India",
    genre: "Beach",
    geometry: { type: "Point", coordinates: [73.8567, 15.4909] },
  },
  {
    title: "Shillong Pinewood Retreat",
    description: "Cozy wooden cabin nestled in a pine forest. Perfect for misty mountain mornings, hammock lounging and complete digital detox.",
    image: { url: "https://res.cloudinary.com/dgu8te3bn/image/upload/v1770853712/Homekuti_DEV/t9r9etmuhkxor4seitak.jpg", filename: "Homekuti_DEV/t9r9etmuhkxor4seitak" },
    price: 1800, location: "Shillong", country: "India",
    genre: "Forest",
    geometry: { type: "Point", coordinates: [91.8933, 25.5788] },
  },
  {
    title: "Himalayan Ridge Resort",
    description: "Resort offering panoramic Himalayan views, bonfire evenings, and guided treks. The ultimate mountain escape.",
    image: { url: "https://res.cloudinary.com/dgu8te3bn/image/upload/v1770853711/Homekuti_DEV/a1sj1lfxpijfkrjl60jz.jpg", filename: "Homekuti_DEV/a1sj1lfxpijfkrjl60jz" },
    price: 3200, location: "Manali", country: "India",
    genre: "Mountain",
    geometry: { type: "Point", coordinates: [77.1892, 32.2396] },
  },
  {
    title: "Beachside Luxury Bungalow",
    description: "Wake up to the sound of waves in this luxury seafront bungalow. Private beach access, infinity pool, and sunset views included.",
    image: { url: "https://res.cloudinary.com/dgu8te3bn/image/upload/v1770853714/Homekuti_DEV/vschklx2zjsy3kyfljxl.jpg", filename: "Homekuti_DEV/vschklx2zjsy3kyfljxl" },
    price: 4500, location: "Kovalam", country: "India",
    genre: "Beach",
    geometry: { type: "Point", coordinates: [76.9987, 8.3988] },
  },
  {
    title: "Coorg Coffee Estate Cottage",
    description: "Stay amidst a working coffee plantation in the Scotland of India. Morning coffee walks, mist-covered hills, and homemade breakfast.",
    image: { url: "https://res.cloudinary.com/dgu8te3bn/image/upload/v1770853715/Homekuti_DEV/o8hhwpxmsmb579fi7izq.jpg", filename: "Homekuti_DEV/o8hhwpxmsmb579fi7izq" },
    price: 1500, location: "Coorg", country: "India",
    genre: "Countryside",
    geometry: { type: "Point", coordinates: [75.7377, 12.3375] },
  },
  {
    title: "Udaipur Lake Palace View",
    description: "Boutique villa with stunning Lake Pichola views. Rooftop dining, vintage decor, and boat rides to the iconic Lake Palace.",
    image: { url: "https://res.cloudinary.com/dgu8te3bn/image/upload/v1771003245/Homekuti_DEV/kzjbrisg2uqssvvp99a3.jpg", filename: "Homekuti_DEV/kzjbrisg2uqssvvp99a3" },
    price: 3800, location: "Udaipur", country: "India",
    genre: "Luxury",
    geometry: { type: "Point", coordinates: [73.6833, 24.5854] },
  },
  {
    title: "Mumbai Budget Studio",
    description: "Clean, well-connected studio apartment in Bandra. Walking distance to cafes, nightlife, and the famous Bandra-Worli Sea Link.",
    image: { url: "https://res.cloudinary.com/dgu8te3bn/image/upload/v1770853714/Homekuti_DEV/vschklx2zjsy3kyfljxl.jpg", filename: "Homekuti_DEV/vschklx2zjsy3kyfljxl" },
    price: 900, location: "Mumbai", country: "India",
    genre: "Budget",
    geometry: { type: "Point", coordinates: [72.8562, 19.0176] },
  },
  {
    title: "Rann of Kutch Desert Camp",
    description: "Luxury tented camp on the edge of the great white desert. Camel rides, folk performances, and a sky full of stars await you.",
    image: { url: "https://res.cloudinary.com/dgu8te3bn/image/upload/v1770853711/Homekuti_DEV/a1sj1lfxpijfkrjl60jz.jpg", filename: "Homekuti_DEV/a1sj1lfxpijfkrjl60jz" },
    price: 2600, location: "Rann of Kutch", country: "India",
    genre: "Desert",
    geometry: { type: "Point", coordinates: [70.1600, 23.8530] },
  },
  {
    title: "Delhi Heritage Haveli",
    description: "Live like a Mughal in this beautifully restored 200-year-old haveli in Shahjahanabad. Just steps from Chandni Chowk.",
    image: { url: "https://res.cloudinary.com/dgu8te3bn/image/upload/v1771086037/Homekuti_DEV/pkrc2pivxsp5l56swdob.webp", filename: "Homekuti_DEV/pkrc2pivxsp5l56swdob" },
    price: 2100, location: "Delhi", country: "India",
    genre: "City",
    geometry: { type: "Point", coordinates: [77.2090, 28.6139] },
  },
  {
    title: "Andaman Island Eco Hut",
    description: "Sustainable bamboo hut on a secluded island beach. Snorkelling, kayaking, and bioluminescent bay nights included.",
    image: { url: "https://res.cloudinary.com/dgu8te3bn/image/upload/v1770853715/Homekuti_DEV/o8hhwpxmsmb579fi7izq.jpg", filename: "Homekuti_DEV/o8hhwpxmsmb579fi7izq" },
    price: 3400, location: "Havelock Island", country: "India",
    genre: "Island",
    geometry: { type: "Point", coordinates: [92.9996, 12.0268] },
  },
  {
    title: "Ooty Nilgiri Retreat",
    description: "Colonial bungalow in the Blue Mountains surrounded by tea gardens. Perfect weather year-round with hiking trails at your doorstep.",
    image: { url: "https://res.cloudinary.com/dgu8te3bn/image/upload/v1770853712/Homekuti_DEV/t9r9etmuhkxor4seitak.jpg", filename: "Homekuti_DEV/t9r9etmuhkxor4seitak" },
    price: 2000, location: "Ooty", country: "India",
    genre: "Mountain",
    geometry: { type: "Point", coordinates: [76.6950, 11.4102] },
  },
];

module.exports = { data: sampleListings };
